version: '3'

services:
  database:
    image: 'postgis/postgis:latest'
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
      POSTGRES_DB: ilgisa2023
    volumes:
      - db-data:/var/lib/postgresql/data/

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'josh@ilgisa2023.com'
      PGADMIN_DEFAULT_PASSWORD: 'ilgisa2023'
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 55433:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database

  imposm:
    image: 'alpine'
    stdin_open: true
    tty: true
    network_mode: 'host'
    volumes:
      - ./imposm:/usr/local/imposm

volumes:
  db-data:
  pgadmin: