version: '3'

services:
  database:
    image: 'postgis/postgis'
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
      POSTGRES_DB: ilgisa2023
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  imposm:
    image: 'golang'
    volumes:
      - .:/usr/local/imposm

volumes:
  db-data: