version: '3'

services:
  database:
    image: 'postgis/postgis:latest'
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
      POSTGRES_DB: ilgisa2023
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - osm  

  osm:
    image: 'dlimkin/osm-tools:latest'
    volumes:
      - ./app:/app
    tty: true
    networks:
      - osm

  slideshow:
    image: 'webpronl/reveal-md:latest'
    ports:
      - 1948:1948
    volumes:
      - ./presentation:/slides

volumes:
  db-data:

networks:
  osm:
    driver: bridge